---
title: "Homework_09"
author: "Ashley Lantigua"
date: "2023-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Use structured Programing 


```{r}
#loading 

  library(ggplot2)

#Annotated Functions

##############################
# FUNCTION: simboxplot2
# purpose: To simulate data for a box plot and perform anova analysis
# input: name, size, mean, S.D.
# output:  The box plot 
#-------------------- 
simboxplot2 <- function(name1, name2, size1, size2, mean1, mean2, sd1, sd2) {
  
  #Name of Groups 
  nName <- c(name1, name2 )
  
  #Number of Observations in each group
  nSize <- c(size1, size2)
  
  #Mean of each group
  nMean <- c(mean1, mean2)
  
  #Standard Deviation of each group
  nSD <- c(sd1, sd2)
  
  #ID vector for each row
  
  ID <- 1:(sum(nSize))
  resVar <- c(rnorm(n=nSize[1], mean=nMean[1], sd=nSD[1]),
              rnorm(n=nSize[2], mean=nMean[2], sd=nSD[2])) 
  
  TGroup <- rep(nName, nSize)
  ANOdata <- data.frame(ID,TGroup,resVar)
  
  #Plotting ANOVA data
  
  ANOplot <- ggplot(data=ANOdata,aes(x=TGroup, y=resVar, FILL=TGroup)) + 
    geom_boxplot()

  
  #Modeling ANOVA data
  
  ANOmodel <- aov(resVar~TGroup, data = ANOdata)
  print(summary(ANOmodel))
  aggregate(resVar~TGroup,data=ANOdata,FUN = mean)
  #unlist(z)
  #z
  #unlist(z)[7]
  #ANOsum <- list(Fval = unlist(z)[7], 
   #              probF = unlist(z)[9])
  #ANOsum
  
  #Basic ggplot of ANOVA data
  
  ANOPlot <- ggplot(data=ANOdata,
                    aes(x=TGroup,
                        y=resVar,
                        fill=TGroup)) +
    geom_boxplot()
  print(ANOPlot)

}

#############################################

#Preliminary Calls 

#Global Variables 

  name1 <- "Control-WT"
  name2 <- "ABA-WT"
    
  size1 <- 30
  size2 <- 30
    
  mean1 <- 6.5
  mean2 <- 3.5
    
  sd1 <- 0.125
  sd2 <- 0.125

#Daisy Chain of the Functions 

  
  #Testing out the function to look at random variability
  
  #run 1
  simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)
  
  #run 2
   simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)
  
   #run 3
    simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)
  
  #Changing the mean 
    
    #Testing the distance of 0.5
    
    mean1 <- 6.5
    mean2 <- 6
    
    simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)
    
    #Testing the distance of 0.06
  
    mean1 <- 6.5
    mean2 <- 6.44
    
    simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)
    
    #Testing the distance of  0.05
    
    mean1 <- 6.5
    mean2 <- 6.45
    
    simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)
    
  #Changing the sample size 
    
    #Testing sample size of 50
    
    size1 <- 50
    size2 <- 50
    
    simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)
    
    #Testing sample size of 35
    
    size1 <- 35
    size2 <- 35
    
    simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)

    #Testing sample size of 37
    
    size1 <- 37
    size2 <- 37
    
    simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)
    
  #Running Randomization 3 times to look at variability 
    
    #run 1
    
    simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)
    
    
    #run 2
    
    simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)
    
    
    #run 3
    simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)

```

## Modify Program to record a new summary variable, code a new statistical analysis, or create a different set of random variables or output graph.  
## Creating a summary variable for the simboxplot2 


```{r}

# Creating a summary variable 
  #for p - value 

  #loading 

  library(ggplot2)

#Annotated Functions

##############################
# FUNCTION: simboxplot2
# purpose: To simulate data for a box plot and perform anova analysis
# input: name, size, mean, S.D.
# output:  The box plot 
#-------------------- 
simboxplot2 <- function(name1, name2, size1, size2, mean1, mean2, sd1, sd2) {
  
  #Name of Groups 
  nName <- c(name1, name2 )
  
  #Number of Observations in each group
  nSize <- c(size1, size2)
  
  #Mean of each group
  nMean <- c(mean1, mean2)
  
  #Standard Deviation of each group
  nSD <- c(sd1, sd2)
  
  #ID vector for each row
  
  ID <- 1:(sum(nSize))
  resVar <- c(rnorm(n=nSize[1], mean=nMean[1], sd=nSD[1]),
              rnorm(n=nSize[2], mean=nMean[2], sd=nSD[2])) 
  
  TGroup <- rep(nName, nSize)
  ANOdata <- data.frame(ID,TGroup,resVar)
  
  #Plotting ANOVA data
  
  ANOplot <- ggplot(data=ANOdata,aes(x=TGroup, y=resVar, FILL=TGroup)) + 
    geom_boxplot()

  
  #Modeling ANOVA data
  
  ANOmodel <- aov(resVar~TGroup, data = ANOdata)
  ANOVAsummary <- print(summary(ANOmodel))
  
  
  
  aggregate(resVar~TGroup,data=ANOdata,FUN = mean)
  #unlist(z)
  #z
  #unlist(z)[7]
  #ANOsum <- list(Fval = unlist(z)[7], 
   #             probF = unlist(z)[9])
  #ANOsum
  
  #Basic ggplot of ANOVA data
  
  ANOPlot <- ggplot(data=ANOdata,
                    aes(x=TGroup,
                        y=resVar,
                        fill=TGroup)) +
    geom_boxplot()
  print(ANOPlot)
  
  pvalue <- unlist(ANOVAsummary)[9]
  
  samplesize1 <- size1

  samplesize2 <- size2
  
  meandf <- abs(mean1 - mean2)
  
  Name <- c("p-value", "sample size 1", "sample size 2", "difference in mean")
  
  Result <- c(pvalue, samplesize1, samplesize2, meandf)
  
  boxplot2_summary <- data.frame(Name, Result)
  
  print(boxplot2_summary)

}

#############################################

#Preliminary Calls 

 options("scipen"= 10, "digits"=2)

#Global Variables 

  name1 <- "Control-WT"
  name2 <- "ABA-WT"
    
  size1 <- 30
  size2 <- 30
    
  mean1 <- 6.5
  mean2 <- 3.5
    
  sd1 <- 0.125
  sd2 <- 0.125


  simboxplot2(name1 = name1, name2 = name2, size1 = size1, size2 = size2, mean1 = mean1, mean2 = mean2, sd1 = sd1, sd2 = sd2)
  


```

